version: "3"
services:
  prometheus:
    tty: true
    container_name: PROMETHEUS
    hostname: PROMETHEUS
    build:
      dockerfile: Dockerfile.prom
    restart: unless-stopped
    ports:
      - "9090:9090"
      - "9092:9092"
      - "9100:9100"
      - "9115:9115"
    volumes:
      - ./configs:/var/node/
    command: "/bin/bash"
    networks:
      - prometheus-network

  grafana:
    tty: true
    container_name: GRAFANA
    hostname: GRAFANA
    build:
      dockerfile: Dockerfile.graf
    restart: unless-stopped
    ports:
      - "9091:3000"
    networks:
      - prometheus-network
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel

volumes:
  configs:

networks:
  prometheus-network:
