version: "3"
services:
  influxdb:
    tty: true
    container_name: INFLUXDB
    hostname: INFLUXDB
    build: 
      dockerfile: Dockerfile.flux
    restart: unless-stopped
    ports:
      - '8086:8086'
    volumes:
      - flux:/var/lib/influxdb
    networks:
      - prometheus-network
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
  prometheus:
    tty: true
    container_name: PROMETHEUS
    hostname: PROMETHEUS
    build:
      dockerfile: Dockerfile.prom
    restart: unless-stopped
    ports:
      - "9090:9090"
      - "9092:9092"
      - "9100:9100"
      - "9115:9115"
    command: "/bin/bash"
    networks:
      - prometheus-network

  grafana:
    tty: true
    container_name: GRAFANA
    hostname: GRAFANA
    build:
      dockerfile: Dockerfile.graf
    restart: unless-stopped
    ports:
      - "9091:3000"
    networks:
      - prometheus-network
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel

volumes:
  flux:
  prom:

networks:
  prometheus-network:
