
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute. 
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:

  - job_name: 'Package Test Lab'
    static_configs:
      - targets: ['192.168.39.100:9182']
      - targets: ['192.168.39.140:9182']
      - targets: ['192.168.39.140:9100']
      - targets: ['192.168.39.162:9182']

  - job_name: 'PROMETHEUS_HOST'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'SelectSurvey.NET'
    metrics_path: /probe
    params:
        module: [http_2xx]
    static_configs:
        - targets:
            - https://www.providence.org
            - https://www.google.com
            - http://subrock.net
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # The blackbox exporter's real hostname:port.



